name: link_hook
description: "A new Dart FFI package project."
version: 0.0.1

environment:
  sdk: '>=3.5.0-154.0.dev <4.0.0'

dependencies:
  cli_config: 0.2.0
  logging: 1.2.0
  # TODO(dacoharkes): Publish versions and don't use git dep.
  native_assets_cli:
    git:
      url: https://dart.googlesource.com/native
      ref: c1b13c3f77f7602e3875f84e2051b8ff8e94ec4c
      path: pkgs/native_assets_cli/
  native_toolchain_c:
    git:
      url: https://dart.googlesource.com/native
      ref: c1b13c3f77f7602e3875f84e2051b8ff8e94ec4c
      path: pkgs/native_toolchain_c/

dev_dependencies:
  ffi: 2.1.2
  ffigen: ^12.0.0
  flutter_lints: ^4.0.0
  test: 1.25.5
