name: link_hook
description: "A new Dart FFI package project."
version: 0.0.1

environment:
  sdk: '>=3.5.0-154.0.dev <4.0.0'

dependencies:
  cli_config: 0.2.0
  logging: 1.2.0
  native_assets_cli: 0.6.0
  native_toolchain_c: 0.4.2

dev_dependencies:
  ffi: 2.1.2
  ffigen: ^12.0.0
  flutter_lints: ^4.0.0
  test: 1.25.5
